---
- name: instance creation
  ec2:
    key_name: "{{ keypair }}"
    region: "{{ region }}"
    instance_tags: "{{ tags }}"
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: "{{ public_ip }}"
    group: "{{ sg }}"
    wait: True
  register: ec2

- add_host: 
    hostname: "{{ item.public_ip }}" 
    groupname: "new_node"
  with_items: "{{ ec2.instances }}"

- name: wait for new_node ssh connection
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22  
    delay: 15
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"